// projects/react/src/components/GenreListComponent.js
import React, {useEffect, useState} from 'react';
import bookService from "../services/BookService";

const GenreListComponent = () => {
    const [genres, setGenres] = useState([]);
    const title = "Жанры"
    const [status, setStatus] = useState('')

    useEffect(() => {
        setStatus("Загрузка...")
        getGenres();
    }, [])
    const getGenres = () => {
        bookService.getGenres().then((res) => {
            setGenres(res.data)
            setStatus("Пусто")
        }).catch(error => {
            console.log(error)
        })
    }
    return (<div>
            <h1 className="text-center" style={{paddingTop: 30}}> {title}</h1>
            <div className="card">
                <div className="card-body">
                    <table className="table table-bordered table-striped ">
                        <thead>
                        <tr>
                            <th className="text-center">
                                Жанр
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {genres.length !== 0 ? genres.map(genre => <tr>
                            <td>
                                {genre.name}
                            </td>
                        </tr>) : <tr>
                            <td className="text-center">
                                {status}
                            </td>
                        </tr>}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>);
};

export default GenreListComponent;

// projects/angular/src/app/genre-list/genre-list.component.ts
import {Component, OnInit} from '@angular/core';
import {BookService} from "../book.service";
import {Genre} from "../genre";
import {Book} from "../book";
import {HttpErrorResponse} from "@angular/common/http";

@Component({
  selector: 'app-genre-list',
  templateUrl: './genre-list.component.html',
  styleUrls: ['./genre-list.component.css']
})
export class GenreListComponent implements OnInit {
  public genres: Genre[] = [];

  constructor(private bookService: BookService) {
  }

  ngOnInit(): void {
    this.getGenres();
  }

  public getGenres(): void {
    this.bookService.findAllGenres().subscribe(
      (response: Genre[]) => {
        this.genres = response;
        console.log(this.genres);
      },
      (error: HttpErrorResponse) => {
        alert(error.message);
      }
    );
  }
}

<h1 class="text-center" style="margin:10px"> Жанры </h1>
<div class="card my-5">
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col">Жанр</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let genre of genres">
        <td>{{ genre.name }}</td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
