// projects/angular/src/app/author-list/author-list.component.ts
import {Component, OnInit} from '@angular/core';
import {Genre} from "../genre";
import {BookService} from "../book.service";
import {HttpErrorResponse} from "@angular/common/http";
import {Author} from "../author";

@Component({
  selector: 'app-author-list',
  templateUrl: './author-list.component.html',
  styleUrls: ['./author-list.component.css']
})
export class AuthorListComponent implements OnInit {

  public authors: Author[] = [];

  constructor(private bookService: BookService) {
  }

  ngOnInit(): void {
    this.getAuthors();
  }

  public getAuthors(): void {
    this.bookService.findAllAuthors().subscribe(
      (response: Genre[]) => {
        this.authors = response;
        console.log(this.authors);
      },
      (error: HttpErrorResponse) => {
        alert(error.message);
      }
    );
  }
}

<h1 class="text-center"> Авторы </h1>
<div class="card my-5">
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col">Автор</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let author of authors">
        <td>{{ author.name }}</td>
      </tr>

      </tbody>
    </table>
  </div>
</div>

// projects/react/src/components/AuthorListComponent.js
import React, {useEffect, useState} from 'react';
import bookService from "../services/BookService";

const AuthorListComponent = () => {
    const [authors, setAuthors] = useState([]);
    const [status, setStatus] = useState('')
    const title = "Авторы"

    useEffect(() => {
        setStatus("Загрузка...")
        getAuthors();
    }, [])
    const getAuthors = () => {
        bookService.getAuthors().then((res) => {
            setAuthors(res.data)
            setStatus("Пусто")
        }).catch(error => {
            console.log(error)
        })
    }
    return (
        <div>
            <h1 className="text-center" style={{paddingTop: 30}}> {title}</h1>
            <div className="card">
                <div className="card-body">
                    <table className="table table-bordered table-striped ">
                        <thead>
                        <tr>
                            <th className="text-center">
                                Автор
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {
                            authors.length !== 0 ?
                                authors.map(author =>
                                    <tr>
                                        <td>
                                            {author.name}
                                        </td>
                                    </tr>
                                ) :
                                <tr>
                                    <td className="text-center">
                                        {status}
                                    </td>
                                </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default AuthorListComponent;
